// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/proto/flow.proto

package go_micro_flow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97d37c2a327f0e0, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CreateStepRequest struct {
	Flow                 string   `protobuf:"bytes,1,opt,name=flow,proto3" json:"flow,omitempty"`
	Step                 *Step    `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStepRequest) Reset()         { *m = CreateStepRequest{} }
func (m *CreateStepRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStepRequest) ProtoMessage()    {}
func (*CreateStepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97d37c2a327f0e0, []int{1}
}

func (m *CreateStepRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStepRequest.Unmarshal(m, b)
}
func (m *CreateStepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStepRequest.Marshal(b, m, deterministic)
}
func (m *CreateStepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStepRequest.Merge(m, src)
}
func (m *CreateStepRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStepRequest.Size(m)
}
func (m *CreateStepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStepRequest proto.InternalMessageInfo

func (m *CreateStepRequest) GetFlow() string {
	if m != nil {
		return m.Flow
	}
	return ""
}

func (m *CreateStepRequest) GetStep() *Step {
	if m != nil {
		return m.Step
	}
	return nil
}

type DeleteStepRequest struct {
	Flow                 string   `protobuf:"bytes,1,opt,name=flow,proto3" json:"flow,omitempty"`
	Step                 *Step    `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStepRequest) Reset()         { *m = DeleteStepRequest{} }
func (m *DeleteStepRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStepRequest) ProtoMessage()    {}
func (*DeleteStepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97d37c2a327f0e0, []int{2}
}

func (m *DeleteStepRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStepRequest.Unmarshal(m, b)
}
func (m *DeleteStepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStepRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStepRequest.Merge(m, src)
}
func (m *DeleteStepRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStepRequest.Size(m)
}
func (m *DeleteStepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStepRequest proto.InternalMessageInfo

func (m *DeleteStepRequest) GetFlow() string {
	if m != nil {
		return m.Flow
	}
	return ""
}

func (m *DeleteStepRequest) GetStep() *Step {
	if m != nil {
		return m.Step
	}
	return nil
}

type UpdateStepRequest struct {
	Flow                 string   `protobuf:"bytes,1,opt,name=flow,proto3" json:"flow,omitempty"`
	Step                 *Step    `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStepRequest) Reset()         { *m = UpdateStepRequest{} }
func (m *UpdateStepRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStepRequest) ProtoMessage()    {}
func (*UpdateStepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97d37c2a327f0e0, []int{3}
}

func (m *UpdateStepRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStepRequest.Unmarshal(m, b)
}
func (m *UpdateStepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStepRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStepRequest.Merge(m, src)
}
func (m *UpdateStepRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStepRequest.Size(m)
}
func (m *UpdateStepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStepRequest proto.InternalMessageInfo

func (m *UpdateStepRequest) GetFlow() string {
	if m != nil {
		return m.Flow
	}
	return ""
}

func (m *UpdateStepRequest) GetStep() *Step {
	if m != nil {
		return m.Step
	}
	return nil
}

type Test struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97d37c2a327f0e0, []int{4}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Steps struct {
	Steps                []*Step  `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Steps) Reset()         { *m = Steps{} }
func (m *Steps) String() string { return proto.CompactTextString(m) }
func (*Steps) ProtoMessage()    {}
func (*Steps) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97d37c2a327f0e0, []int{5}
}

func (m *Steps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Steps.Unmarshal(m, b)
}
func (m *Steps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Steps.Marshal(b, m, deterministic)
}
func (m *Steps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Steps.Merge(m, src)
}
func (m *Steps) XXX_Size() int {
	return xxx_messageInfo_Steps.Size(m)
}
func (m *Steps) XXX_DiscardUnknown() {
	xxx_messageInfo_Steps.DiscardUnknown(m)
}

var xxx_messageInfo_Steps proto.InternalMessageInfo

func (m *Steps) GetSteps() []*Step {
	if m != nil {
		return m.Steps
	}
	return nil
}

type Step struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Requires             []string     `protobuf:"bytes,2,rep,name=requires,proto3" json:"requires,omitempty"`
	Required             []string     `protobuf:"bytes,3,rep,name=required,proto3" json:"required,omitempty"`
	Operations           []*Operation `protobuf:"bytes,4,rep,name=operations,proto3" json:"operations,omitempty"`
	Fallback             []*Operation `protobuf:"bytes,5,rep,name=fallback,proto3" json:"fallback,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Step) Reset()         { *m = Step{} }
func (m *Step) String() string { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()    {}
func (*Step) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97d37c2a327f0e0, []int{6}
}

func (m *Step) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Step.Unmarshal(m, b)
}
func (m *Step) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Step.Marshal(b, m, deterministic)
}
func (m *Step) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Step.Merge(m, src)
}
func (m *Step) XXX_Size() int {
	return xxx_messageInfo_Step.Size(m)
}
func (m *Step) XXX_DiscardUnknown() {
	xxx_messageInfo_Step.DiscardUnknown(m)
}

var xxx_messageInfo_Step proto.InternalMessageInfo

func (m *Step) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Step) GetRequires() []string {
	if m != nil {
		return m.Requires
	}
	return nil
}

func (m *Step) GetRequired() []string {
	if m != nil {
		return m.Required
	}
	return nil
}

func (m *Step) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *Step) GetFallback() []*Operation {
	if m != nil {
		return m.Fallback
	}
	return nil
}

type Operation struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string            `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Options              map[string]string `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_c97d37c2a327f0e0, []int{7}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Operation) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Operation) GetOptions() map[string]string {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "go.micro.flow.Empty")
	proto.RegisterType((*CreateStepRequest)(nil), "go.micro.flow.CreateStepRequest")
	proto.RegisterType((*DeleteStepRequest)(nil), "go.micro.flow.DeleteStepRequest")
	proto.RegisterType((*UpdateStepRequest)(nil), "go.micro.flow.UpdateStepRequest")
	proto.RegisterType((*Test)(nil), "go.micro.flow.Test")
	proto.RegisterType((*Steps)(nil), "go.micro.flow.Steps")
	proto.RegisterType((*Step)(nil), "go.micro.flow.Step")
	proto.RegisterType((*Operation)(nil), "go.micro.flow.Operation")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.flow.Operation.OptionsEntry")
}

func init() { proto.RegisterFile("service/proto/flow.proto", fileDescriptor_c97d37c2a327f0e0) }

var fileDescriptor_c97d37c2a327f0e0 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc7, 0xc9, 0x17, 0x6d, 0x06, 0x90, 0xc0, 0xf4, 0x60, 0xe5, 0x14, 0x45, 0x42, 0x94, 0x4b,
	0x2a, 0x15, 0x24, 0xaa, 0x5e, 0x38, 0x40, 0x7b, 0x2d, 0x0a, 0xf0, 0x00, 0x69, 0x3a, 0x45, 0x51,
	0xd3, 0xda, 0x75, 0x9c, 0x42, 0x9e, 0x64, 0x5f, 0x63, 0x9f, 0x61, 0x9f, 0x6c, 0x65, 0xa7, 0xe9,
	0x57, 0x9a, 0xdd, 0x4b, 0x6f, 0x33, 0x9e, 0xff, 0xfc, 0x66, 0x12, 0xff, 0x0d, 0x34, 0x47, 0xb1,
	0x4b, 0x13, 0x1c, 0x70, 0xc1, 0x24, 0x1b, 0x2c, 0x33, 0xf6, 0x2f, 0xd4, 0x21, 0x79, 0xf3, 0x97,
	0x85, 0xeb, 0x34, 0x11, 0x2c, 0x54, 0x87, 0x41, 0x07, 0x9c, 0xc9, 0x9a, 0xcb, 0x32, 0xf8, 0x09,
	0xef, 0xbe, 0x0b, 0x8c, 0x25, 0xfe, 0x92, 0xc8, 0x23, 0xdc, 0x16, 0x98, 0x4b, 0x42, 0xc0, 0x56,
	0x2a, 0x6a, 0xf8, 0x46, 0xdf, 0x8d, 0x74, 0x4c, 0x3e, 0x82, 0x9d, 0x4b, 0xe4, 0xd4, 0xf4, 0x8d,
	0xfe, 0xab, 0xe1, 0xfb, 0xf0, 0x8c, 0x17, 0xea, 0x6e, 0x2d, 0x50, 0xc4, 0x1f, 0x98, 0xe1, 0x6d,
	0x89, 0x7f, 0xf8, 0xe2, 0x96, 0x3b, 0x7a, 0x60, 0xff, 0xde, 0x43, 0x36, 0xf1, 0x1a, 0x6b, 0x88,
	0x8a, 0x83, 0x21, 0x38, 0x4a, 0x99, 0x93, 0x4f, 0xe0, 0x28, 0x71, 0x4e, 0x0d, 0xdf, 0x6a, 0xc3,
	0x55, 0x8a, 0xe0, 0xc1, 0x00, 0x5b, 0xe5, 0xd7, 0x80, 0xc4, 0x83, 0xae, 0xc0, 0x6d, 0x91, 0x0a,
	0xcc, 0xa9, 0xe9, 0x5b, 0x7d, 0x37, 0x3a, 0xe4, 0x27, 0xb5, 0x05, 0xb5, 0xce, 0x6a, 0x0b, 0x32,
	0x02, 0x60, 0x1c, 0x45, 0x2c, 0x53, 0xb6, 0xc9, 0xa9, 0xad, 0x97, 0xa0, 0x17, 0x4b, 0xcc, 0x6a,
	0x41, 0x74, 0xa2, 0x25, 0x5f, 0xa0, 0xbb, 0x8c, 0xb3, 0x6c, 0x1e, 0x27, 0x2b, 0xea, 0x3c, 0xd3,
	0x77, 0x50, 0x06, 0xf7, 0x06, 0xb8, 0x87, 0xf3, 0xab, 0x5f, 0x42, 0xc0, 0x96, 0x25, 0x47, 0xfd,
	0x7f, 0xdd, 0x48, 0xc7, 0xe4, 0x1b, 0x74, 0x18, 0xaf, 0x56, 0xb4, 0xf4, 0xa8, 0x0f, 0x6d, 0xa3,
	0xc2, 0x59, 0xa5, 0x9b, 0x6c, 0xa4, 0x28, 0xa3, 0xba, 0xcb, 0x1b, 0xc3, 0xeb, 0xd3, 0x02, 0x79,
	0x0b, 0xd6, 0x0a, 0xcb, 0xfd, 0x5c, 0x15, 0x92, 0x1e, 0x38, 0xbb, 0x38, 0x2b, 0xea, 0xb9, 0x55,
	0x32, 0x36, 0x47, 0xc6, 0xf0, 0xce, 0x04, 0x7b, 0xaa, 0x6e, 0x7e, 0x0a, 0x70, 0xb4, 0x31, 0xf1,
	0x2f, 0x56, 0x68, 0x38, 0xdc, 0xeb, 0x5d, 0x28, 0xaa, 0xc7, 0xf0, 0x42, 0x71, 0x8e, 0xe6, 0x6d,
	0x70, 0x1a, 0xbe, 0x7e, 0x8a, 0x73, 0xb4, 0x6c, 0x83, 0xd3, 0x70, 0x73, 0x2b, 0xe7, 0x2b, 0x74,
	0x26, 0xff, 0x31, 0x29, 0x24, 0x92, 0xab, 0x92, 0xb6, 0xc6, 0xf9, 0x4b, 0xfd, 0xec, 0x3f, 0x3f,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x2d, 0x3b, 0x90, 0x12, 0x04, 0x00, 0x00,
}
