// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: agent/proto/schedule.proto

package agent

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v6/client"
	server "go-micro.dev/v6/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AgentSchedules service

type AgentSchedulesService interface {
	Add(ctx context.Context, in *AddScheduleRequest, opts ...client.CallOption) (*ScheduleResponse, error)
	List(ctx context.Context, in *ListSchedulesRequest, opts ...client.CallOption) (*ListSchedulesResponse, error)
	Remove(ctx context.Context, in *RemoveScheduleRequest, opts ...client.CallOption) (*RemoveScheduleResponse, error)
}

type agentSchedulesService struct {
	c    client.Client
	name string
}

func NewAgentSchedulesService(name string, c client.Client) AgentSchedulesService {
	return &agentSchedulesService{
		c:    c,
		name: name,
	}
}

func (c *agentSchedulesService) Add(ctx context.Context, in *AddScheduleRequest, opts ...client.CallOption) (*ScheduleResponse, error) {
	req := c.c.NewRequest(c.name, "AgentSchedules.Add", in)
	out := new(ScheduleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSchedulesService) List(ctx context.Context, in *ListSchedulesRequest, opts ...client.CallOption) (*ListSchedulesResponse, error) {
	req := c.c.NewRequest(c.name, "AgentSchedules.List", in)
	out := new(ListSchedulesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentSchedulesService) Remove(ctx context.Context, in *RemoveScheduleRequest, opts ...client.CallOption) (*RemoveScheduleResponse, error) {
	req := c.c.NewRequest(c.name, "AgentSchedules.Remove", in)
	out := new(RemoveScheduleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgentSchedules service

type AgentSchedulesHandler interface {
	Add(context.Context, *AddScheduleRequest, *ScheduleResponse) error
	List(context.Context, *ListSchedulesRequest, *ListSchedulesResponse) error
	Remove(context.Context, *RemoveScheduleRequest, *RemoveScheduleResponse) error
}

func RegisterAgentSchedulesHandler(s server.Server, hdlr AgentSchedulesHandler, opts ...server.HandlerOption) error {
	type agentSchedules interface {
		Add(ctx context.Context, in *AddScheduleRequest, out *ScheduleResponse) error
		List(ctx context.Context, in *ListSchedulesRequest, out *ListSchedulesResponse) error
		Remove(ctx context.Context, in *RemoveScheduleRequest, out *RemoveScheduleResponse) error
	}
	type AgentSchedules struct {
		agentSchedules
	}
	h := &agentSchedulesHandler{hdlr}
	return s.Handle(s.NewHandler(&AgentSchedules{h}, opts...))
}

type agentSchedulesHandler struct {
	AgentSchedulesHandler
}

func (h *agentSchedulesHandler) Add(ctx context.Context, in *AddScheduleRequest, out *ScheduleResponse) error {
	return h.AgentSchedulesHandler.Add(ctx, in, out)
}

func (h *agentSchedulesHandler) List(ctx context.Context, in *ListSchedulesRequest, out *ListSchedulesResponse) error {
	return h.AgentSchedulesHandler.List(ctx, in, out)
}

func (h *agentSchedulesHandler) Remove(ctx context.Context, in *RemoveScheduleRequest, out *RemoveScheduleResponse) error {
	return h.AgentSchedulesHandler.Remove(ctx, in, out)
}
