name: Lint
on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "**"
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          check-latest: true
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
