name: Build and test micro
on:
  pull_request:
    branches:
      - master

jobs:

  build:
    name: Build and test micro
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go
  
    - name: Install Protoc
      uses: arduino/setup-protoc@master

    - name: Check out this code
      uses: actions/checkout@v2
      with:
        path: 'go-micro'

    - name: Check out micro
      uses: actions/checkout@v2
      with:
        repository: 'micro/micro'
        path: 'micro'

    - name: Build all
      run: $GITHUB_WORKSPACE/go-micro/.github/workflows/scripts/build-micro.sh ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.head.repo.full_name }}
      working-directory: micro
    